# https://pre-commit.com
default_install_hook_types: [commit-msg, pre-commit]
default_stages: [commit, manual]
fail_fast: false
ci:
  skip:
    - pyupgrade
    - absolufy-imports
    - yesqa
    - shellcheck
    - poetry-check

repos:
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations
      - id: python-check-blanket-noqa
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
      - id: text-unicode-replacement-char

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: debug-statements
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
        types: [python]
      - id: end-of-file-fixer
        types: [python]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.7
    hooks:
      - id: prettier

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
      - id: black
        name: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        additional_dependencies:
          - lxml
          - pydantic
          - types-pyyaml
          - types-requests
          - types-setuptools
          - types-toml
        args:
          - --no-warn-unused-ignores

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args:
          - --radon-max-cc=5
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-eradicate
          - flake8-logging-format
          - flake8-mutable
          - flake8-print
          - flake8-pytest-style
          - flake8-tidy-imports
          - radon[toml]
          - setuptools

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        entry: pydocstyle
        additional_dependencies: [toml]

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        entry: bandit
        args:
          - -c
          - pyproject.toml
          - -f
          - html
          - -o
          - docs/reports/bandit.html

        additional_dependencies: [toml]

  - repo: local
    hooks:
      - id: pyupgrade
        name: pyupgrade
        entry: pyupgrade --py38-plus
        require_serial: true
        language: system
        types: [python]
      - id: absolufy-imports
        name: absolufy-imports
        entry: absolufy-imports
        require_serial: true
        language: system
        types: [python]
      - id: yesqa
        name: yesqa
        entry: yesqa
        exclude: src/pyspry/(__init__|base).py
        require_serial: true
        language: system
        types: [python]
      - id: shellcheck
        name: shellcheck
        entry: shellcheck --check-sourced
        language: system
        types: [shell]
      - id: poetry-check
        name: poetry check
        entry: poetry check
        language: system
        files: pyproject.toml
        pass_filenames: false
